'use strict'

module.exports = {
  'vue/block-tag-newline': 'off',
  'vue/component-name-in-template-casing': 'off',
  'vue/custom-event-name-casing': 'off',
  'vue/html-button-has-type': 'error',
  'vue/html-comment-content-newline': 'off',
  'vue/html-comment-content-spacing': 'error',
  'vue/html-comment-indent': [ 'error', 2 ],
  'vue/match-component-file-name': 'off',
  'vue/new-line-between-multi-line-property': 'error',
  'vue/next-tick-style': 'off',
  'vue/no-bare-strings-in-template': 'off',
  'vue/no-boolean-default': 'off',
  'vue/no-duplicate-attr-inheritance': 'error',
  'vue/no-empty-component-block': 'error',
  'vue/no-multiple-objects-in-class': 'error',
  'vue/no-potential-component-option-typo': 'off',
  'vue/no-reserved-component-names': 'error',
  'vue/no-restricted-block': 'off',
  'vue/no-restricted-call-after-await': 'off',
  'vue/no-restricted-component-options': 'error',
  'vue/no-restricted-custom-event': 'off',
  'vue/no-restricted-props': 'off',
  'vue/no-restricted-static-attribute': 'off',
  'vue/no-restricted-v-bind': 'off',
  'vue/no-static-inline-styles': 'error',
  'vue/no-template-target-blank': 'error',
  'vue/no-unregistered-components': 'off',
  'vue/no-unsupported-features': 'off',
  'vue/no-unused-properties': 'off',
  'vue/no-useless-mustaches': [ 'error', {
    ignoreIncludesComment: true,
    ignoreStringEscape: true,
  } ],
  'vue/no-useless-v-bind': 'error',
  'vue/padding-line-between-blocks': 'error',
  'vue/require-direct-export': 'error',
  'vue/require-name-property': 'error',
  'vue/script-indent': [ 'error', 2, {
    baseIndent: 1,
    switchCase: 0,
    ignores: [],
  } ],
  'vue/sort-keys': 'off',
  'vue/static-class-names-order': 'off',
  'vue/v-for-delimiter-style': 'off',
  'vue/v-on-event-hyphenation': 'off',
  'vue/v-on-function-call': 'error',
  'vue/valid-next-tick': 'error',
}
