'use strict'

module.exports = {
  extends: [ 'plugin:vue/base' ],
  settings: {
    'import/resolver': {
      node: {
        extensions: [ '.js', '.json', '.vue' ],
      },
    },
    'import/extensions': [ '.js', '.json', '.vue' ],
  },
  rules: {
    'import/no-anonymous-default-export': 'off',
    'no-multiple-empty-lines': 'off', // doesn't work well with `.vue` files so disable it
    'vue/attribute-hyphenation': [ 'error', 'always' ],
    'vue/attributes-order': 'error',
    'vue/component-name-in-template-casing': 'off',
    'vue/html-closing-bracket-newline': 'off',
    'vue/html-closing-bracket-spacing': [ 'error', {
      startTag: 'never',
      endTag: 'never',
      selfClosingTag: 'always',
    } ],
    'vue/html-end-tags': 'off',
    'vue/html-indent': [ 'error', 2, {
      attribute: 1,
      closeBracket: 1,
      alignAttributesVertically: false,
      ignores: [],
    } ],
    'vue/html-quotes': [ 'error', 'double' ],
    'vue/html-self-closing': 'error', // use the default settings
    'vue/jsx-uses-vars': 'error',
    'vue/max-attributes-per-line': 'off',
    'vue/multiline-html-element-content-newline': 'error',
    'vue/mustache-interpolation-spacing': [ 'error', 'always' ],
    'vue/name-property-casing': 'off',
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-dupe-keys': 'error', // leave options to default
    'vue/no-duplicate-attributes': 'error',
    'vue/no-multi-spaces': 'error',
    'vue/no-parsing-error': 'error',
    'vue/no-reserved-keys': 'error', // leave options to default
    'vue/no-shared-component-data': 'error',
    'vue/no-side-effects-in-computed-properties': 'error',
    'vue/no-spaces-around-equal-signs-in-attribute': 'error',
    'vue/no-template-key': 'error',
    'vue/no-template-shadow': 'error',
    'vue/no-textarea-mustache': 'error',
    'vue/no-unused-components': 'error',
    'vue/no-unused-vars': 'error',
    'vue/no-use-v-if-with-v-for': 'off',
    'vue/no-v-html': 'error',
    'vue/order-in-components': 'error',
    'vue/prop-name-casing': [ 'error', 'camelCase' ],
    'vue/require-component-is': 'error',
    'vue/require-default-prop': 'error',
    'vue/require-prop-type-constructor': 'error',
    'vue/require-prop-types': 'error',
    'vue/require-render-return': 'error',
    'vue/require-v-for-key': 'error',
    'vue/require-valid-default-prop': 'error',
    'vue/return-in-computed-property': [ 'error', {
      treatUndefinedAsUnspecified: true,
    } ],
    'vue/script-indent': [ 'error', 2, {
      baseIndent: 1,
      switchCase: 0,
      ignores: [],
    } ],
    'vue/singleline-html-element-content-newline': 'off',
    'vue/this-in-template': [ 'error', 'never' ],
    'vue/use-v-on-exact': 'error',
    'vue/v-bind-style': [ 'error', 'shorthand' ],
    'vue/v-on-style': [ 'error', 'shorthand' ],
    'vue/valid-template-root': 'error',
    'vue/valid-v-bind': 'error',
    'vue/valid-v-cloak': 'error',
    'vue/valid-v-else': 'error',
    'vue/valid-v-else-if': 'error',
    'vue/valid-v-for': 'error',
    'vue/valid-v-html': 'error',
    'vue/valid-v-if': 'error',
    'vue/valid-v-model': 'error',
    'vue/valid-v-on': 'error',
    'vue/valid-v-once': 'error',
    'vue/valid-v-pre': 'error',
    'vue/valid-v-show': 'error',
    'vue/valid-v-text': 'error',
  },
}
